# Generated by Django 5.2 on 2025-05-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_offensive',
            field=models.BooleanField(default=False),
        ),
    ]
